In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 독립변수, 종속변수 분리
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [7]:
# 3. 데이터로 모델을 학습(fit)합니다.
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 2.7173 - accuracy: 0.0157
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.6906 - accuracy: 0.0053
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.6350 - accuracy: 0.0035
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.4120 - accuracy: 0.0035
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.4679 - accuracy: 0.0000e+00
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.2399 - accuracy: 0.0000e+00
Epoch 7/1000
5/5 [==============================] - 0s 3ms/step - loss: 2.3552 - accuracy: 0.0131
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.4603 - accuracy: 0.0022
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.2244 - accuracy: 0.0053
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 2.2766 - accuracy: 0.0053
Epoch 11/10

In [9]:
# 4. 모델을 이용합니다.
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9906725e-01 9.3268481e-04 6.9549678e-08]
 [9.9564373e-01 4.3554190e-03 7.7216185e-07]
 [9.9823380e-01 1.7659498e-03 2.5316200e-07]
 [9.9615425e-01 3.8448372e-03 9.6364556e-07]
 [9.9933088e-01 6.6913269e-04 4.8632401e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [10]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[5.30389173e-07 1.46989062e-01 8.53010476e-01]
 [1.35722883e-06 2.07910329e-01 7.92088330e-01]
 [3.17613626e-06 2.52070606e-01 7.47926295e-01]
 [9.48780610e-07 1.10725224e-01 8.89273822e-01]
 [1.09560979e-05 2.74659723e-01 7.25329340e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [12]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.15811896,  0.32555002, -0.7283388 ],
       [ 3.2488523 ,  0.09279714, -1.2177383 ],
       [-3.4025261 , -0.99620056,  0.6148469 ],
       [-4.6975126 , -0.64093393,  2.297718  ]], dtype=float32), array([ 1.8829604 ,  0.91857266, -1.466699  ], dtype=float32)]
