In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 독립변수, 종속변수 분리
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [7]:
# 모델 구조 확인
model.summary() # (4+1)*8=40, (8+1)*8=72, (8+1)*3=27

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 3. 데이터로 모델을 학습(fit)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0492 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0429 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0450 - accuracy: 0.9933
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0437 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0450 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0546 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0531 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0503 - accuracy: 0.9867


In [9]:
# 4. 모델을 이용합니다.
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9999964e-01 3.9556801e-07 2.4750987e-15]
 [9.9999726e-01 2.7407407e-06 8.4231918e-14]
 [9.9999893e-01 1.0757641e-06 3.0717491e-14]
 [9.9999559e-01 4.4150697e-06 2.6015629e-13]
 [9.9999964e-01 3.2678599e-07 2.1102102e-15]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [11]:
# weights & bias 출력
weights = model.get_weights()
print(weights)

[array([[ 0.01637618,  0.18502207,  0.37946165,  0.40579987,  0.23949797,
        -0.1524328 , -0.09604204,  0.86693376],
       [-0.32197335,  0.59301335,  0.62314516,  0.5088704 , -0.54936767,
        -0.35722527,  0.06324125, -0.1571859 ],
       [ 0.41841143, -0.5407593 ,  0.487885  , -0.30985987, -0.16604458,
        -0.1110172 ,  0.41828066,  0.2792894 ],
       [ 0.6508132 , -0.2515668 ,  0.37765905, -0.44695717, -1.0163157 ,
        -0.05909336,  0.41734135, -0.15630575]], dtype=float32), array([-0.13611874,  0.28359836, -0.23875192,  0.30871165,  0.01461214,
        0.19280533, -0.14961351,  0.34670493], dtype=float32), array([[-0.83956444,  0.37678257, -0.37092802, -0.54162514,  0.5076783 ,
         0.27827415, -0.44577113, -0.72122115],
       [ 0.70071244,  0.08466338, -0.3728434 , -0.04779973, -0.6930623 ,
         0.3771243 ,  0.47128695,  0.72584367],
       [ 0.2040482 ,  0.10345653, -0.40147218,  0.21971144,  0.41058436,
         0.11507007,  0.17389789, -0.50237405],


cf) https://codetorial.net/tensorflow/get_weights.html

In [13]:
len(weights)

8

In [14]:
for i in range(8):
  print(weights[i].shape)

(4, 8)
(8,)
(8, 8)
(8,)
(8, 8)
(8,)
(8, 3)
(3,)
