# Tensor Manipulation

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

TensorFlow 1.x selected.


## Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() # InteractiveSession에서는 run 대신 eval 사용

array([4], dtype=int32)

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [6]:
tf.shape(t)

<tf.Tensor 'Shape_2:0' shape=(2,) dtype=int32>

In [7]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [8]:
[
 [
  [
   [1, 2, 3, 4],
   [5, 6, 7, 8],
   [9, 10, 11, 12]
   ], 
  [
   [13, 14, 15, 16],
   [17, 18, 19, 20],
   [21, 22, 23, 24]
   ]
  ]
 ]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS Multiply

In [9]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [10]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [12]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

## Random values for variable initializations

In [13]:
tf.random_normal([3]).eval()

array([0.9843767 , 0.4315476 , 0.57160735], dtype=float32)

In [14]:
tf.random_uniform([2]).eval()

array([0.2819959, 0.3318826], dtype=float32)

In [15]:
tf.random_uniform([2, 3]).eval()

array([[0.6818336 , 0.8505827 , 0.57356274],
       [0.0214833 , 0.5632874 , 0.16612053]], dtype=float32)

## Reduce Mean/Sum

In [18]:
tf.reduce_mean([1, 2], axis=0).eval() # int

1

In [16]:
tf.reduce_mean([1., 2.], axis=0).eval() # float

1.5

In [20]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval()

2.5

In [21]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [22]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [23]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [24]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [25]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [26]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [27]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [28]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [29]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

## Reshape, Squeeze, Expand_dims

In [30]:
t = np.array([[[0,1,2],
               [3,4,5]],
              
              [[6,7,8],
               [9,10,11]]])
t.shape

(2, 2, 3)

In [31]:
tf.reshape(t, shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [33]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [38]:
tf.expand_dims([0,1,2], 1).eval() # (3,)

array([[0],
       [1],
       [2]], dtype=int32)

In [37]:
t2 = tf.expand_dims([0,1,2], 1).eval()
t2.shape # (3,)에서 (3, 1)이 됨 

(3, 1)

## One hot

In [39]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() # depth는 클래스 개수

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [41]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [46]:
tf.one_hot([[0], [1], [2], [0]], depth=2).eval()

array([[[1., 0.]],

       [[0., 1.]],

       [[0., 0.]],

       [[1., 0.]]], dtype=float32)

## Casting

In [47]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval() # 반올림 X 

array([1, 2, 3, 4], dtype=int32)

In [48]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

## Stack

In [49]:
x = [1,4]
y = [2,5]
z = [3,6]

# Pack along first dim.
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [51]:
tf.stack([x,y,z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [52]:
tf.stack([x,y,z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones like and Zeros like

In [53]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [54]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip

In [55]:
for x,y in zip([1, 2, 3], [4, 5, 6]):
  print(x, y)

1 4
2 5
3 6


In [56]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
  print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [62]:
t = np.array([[[0,1,2], [3,4,5]], [[6,7,8], [9,10,11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [63]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [60]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [64]:
t3 = tf.transpose(t, [2, 0, 1])
pp.pprint(sess.run(t3).shape)
pp.pprint(sess.run(t3))

(3, 2, 2)
array([[[ 0,  3],
        [ 6,  9]],

       [[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]]])
