In [6]:
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

TensorFlow 1.x selected.


In [7]:
def min_max_scaler(data):
  numerator = data - np.min(data, 0)
  denominator = np.max(data, 0) - np.min(data, 0)
  # noise term prevents the zero division
  return numerator / (denominator + 1e-7)

In [8]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [9]:
# Very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [10]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [11]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [12]:
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [13]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [20]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-1)
train = optimizer.minimize(cost)

In [21]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  0.15230924 
Prediction: 
 [[ 1.6346191 ]
 [ 0.06613702]
 [ 0.35008183]
 [ 0.6707252 ]
 [ 0.6113075 ]
 [ 0.61464405]
 [ 0.23171969]
 [-0.1372836 ]]
1 Cost:  0.14692229 
Prediction: 
 [[ 1.6229731 ]
 [ 0.08020899]
 [ 0.35646972]
 [ 0.66874385]
 [ 0.6120828 ]
 [ 0.61619383]
 [ 0.2348881 ]
 [-0.12564787]]
2 Cost:  0.14178431 
Prediction: 
 [[ 1.6105106 ]
 [ 0.0928998 ]
 [ 0.36177614]
 [ 0.66601324]
 [ 0.61195624]
 [ 0.6168449 ]
 [ 0.237302  ]
 [-0.11495095]]
3 Cost:  0.13687368 
Prediction: 
 [[ 1.5976942 ]
 [ 0.10467464]
 [ 0.36638874]
 [ 0.6628331 ]
 [ 0.61128175]
 [ 0.61694   ]
 [ 0.23919855]
 [-0.10495421]]
4 Cost:  0.13217552 
Prediction: 
 [[ 1.5848047 ]
 [ 0.11582202]
 [ 0.37054732]
 [ 0.65938866]
 [ 0.61027753]
 [ 0.616691  ]
 [ 0.2407264 ]
 [-0.09550622]]
5 Cost:  0.12767783 
Prediction: 
 [[ 1.5720111 ]
 [ 0.12652111]
 [ 0.37440068]
 [ 0.6557944 ]
 [ 0.6090782 ]
 [ 0.6162287 ]
 [ 0.24197952]
 [-0.08650962]]
6 Cost:  0.12337014 
Prediction: 
 [[ 1.5594137 ]
 [ 0.13688377]