In [1]:
%tensorflow_version 1.x
import tensorflow as tf

TensorFlow 1.x selected.


In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

In [6]:
# Lauch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  40655.895 
Prediction:
 [[343.22842]
 [390.3762 ]
 [396.13138]
 [430.69742]
 [292.78503]]
10 Cost:  90.634445 
Prediction:
 [[165.0229 ]
 [176.25587]
 [185.11888]
 [200.91388]
 [129.47932]]
20 Cost:  89.77867 
Prediction:
 [[164.44719]
 [175.6331 ]
 [184.4693 ]
 [200.21022]
 [129.01842]]
30 Cost:  89.29677 
Prediction:
 [[164.40903]
 [175.65625]
 [184.4562 ]
 [200.1997 ]
 [129.05014]]
40 Cost:  88.81758 
Prediction:
 [[164.37257]
 [175.68124]
 [184.44507]
 [200.19131]
 [129.08325]]
50 Cost:  88.34091 
Prediction:
 [[164.33621]
 [175.70618]
 [184.43396]
 [200.18292]
 [129.11627]]
60 Cost:  87.8668 
Prediction:
 [[164.29997]
 [175.73106]
 [184.42291]
 [200.17458]
 [129.14923]]
70 Cost:  87.3953 
Prediction:
 [[164.26384]
 [175.75589]
 [184.4119 ]
 [200.16626]
 [129.1821 ]]
80 Cost:  86.92638 
Prediction:
 [[164.2278 ]
 [175.78064]
 [184.40091]
 [200.15797]
 [129.21487]]
90 Cost:  86.45995 
Prediction:
 [[164.19186]
 [175.80533]
 [184.38994]
 [200.14969]
 [129.24756]]
100 Cost:  