In [1]:
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

TensorFlow 1.x selected.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
xy = np.loadtxt('/content/drive/My Drive/DeepLearningZeroToAll-master/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [6]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [170.5091 ]
 [162.94283]
 [167.38731]
 [194.27454]]
160 Cost: 84.788795 
Prediction:
 [[157.63185 ]
 [185.1952  ]
 [184.92613 ]
 [197.77153 ]
 [143.27342 ]
 [ 99.72923 ]
 [143.99052 ]
 [101.166756]
 [167.75856 ]
 [147.11832 ]
 [141.1847  ]
 [136.00175 ]
 [194.6434  ]
 [166.73846 ]
 [143.63033 ]
 [184.8882  ]
 [161.88145 ]
 [171.41023 ]
 [186.799   ]
 [166.9889  ]
 [169.44986 ]
 [170.53014 ]
 [162.95514 ]
 [167.31485 ]
 [194.26424 ]]
170 Cost: 84.154205 
Prediction:
 [[157.60504]
 [185.19972]
 [184.91005]
 [197.77351]
 [143.26993]
 [ 99.76105]
 [144.01071]
 [101.20677]
 [167.79514]
 [147.1986 ]
 [141.19507]
 [136.03569]
 [194.60745]
 [166.68315]
 [143.65825]
 [184.90799]
 [161.81651]
 [171.43823]
 [186.75597]
 [166.94998]
 [169.47185]
 [170.55107]
 [162.96744]
 [167.24274]
 [194.25397]]
180 Cost: 83.52493 
Prediction:
 [[157.57837 ]
 [185.20422 ]
 [184.89404 ]
 [197.77551 ]
 [143.26642 ]
 [ 99.792694]
 [144.03084 ]
 [101.24663 ]
 [167.83154 ]
 [147.2

In [11]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[181.73276]]
Other scores will be  [[145.86266]
 [187.23131]]
